### ISSUE TITLE
Deprecate and remove the CLI

### ISSUE THREAD

**Issue by iacchus** [iacchus/birdears#40]
There is no need to continue shipping and developing the cli actually as we have the Urwid TUI. The CLI should be deprecated and removed from birdears package.

**Comment by a1ro** [comment]
Hi, first of all, great work on this project!

I've been looking for this kind of software for a long time.
Minimal, keyboard-driven, desktop/laptop ear trainer.
I especially like the "distraction free" nature of the CLI interface.

This weekend I had a look at the code and started adding features.
I have a few small pull requests on the way if you're interested.

In my opinion, the CLI somewhat complements the TUI.
One kinda aims at auditory people and the other at visuals (with more graphical feedback).

Since the CLI interface is already well implemented, I vote to keep it.

**Comment by iacchus** [comment]
Thank you for your feedback. :) I can keep the cli then, just think it needs to be rewritten.

I would like to see your feats, yes.
